# RSICap Dataset Augmentation Configuration
# Each augmentation technique can be controlled via true/false switches

# =============================================================================
# Global Settings
# =============================================================================
aug_prob: 0.8 # Probability of applying augmentation (0.0-1.0)
image_size: 512 # Output image size (maintain original size)

# =============================================================================
# Spatial Transforms
# Suitable for remote sensing images, preserving geographic orientation
# =============================================================================
enable_spatial: true # Master switch: whether to enable spatial transforms

# Random crop (simulate different shooting heights and field of view)
enable_crop: true # Switch: random crop
crop_scale: [0.8, 1.0] # Crop scale range
crop_ratio: [0.9, 1.1] # Aspect ratio range

# Affine transform (small range translation, no rotation to preserve orientation)
enable_affine: true # Switch: affine transform
translate_range: [0.1, 0.1] # Translation range (relative to image size)

# =============================================================================
# 颜色变换 (Color Transforms)
# 模拟不同的光照和大气条件
# =============================================================================
enable_color: true # 总开关：是否启用颜色变换

# 颜色抖动 (模拟不同光照条件)
enable_color_jitter: true # 开关：颜色抖动
brightness: 0.2 # 亮度变化范围
contrast: 0.2 # 对比度变化范围
saturation: 0.1 # 饱和度变化范围
hue: 0.05 # 色调变化范围

# 随机灰度 (模拟单波段图像)
enable_grayscale: true # 开关：随机灰度
grayscale_prob: 0.1 # 转为灰度的概率

# 高斯模糊 (模拟大气散射和传感器模糊)
enable_blur: true # 开关：高斯模糊
blur_kernel: 3 # 模糊核大小
blur_sigma: [0.1, 0.5] # 模糊强度范围

# =============================================================================
# 噪声变换 (Noise Transforms)
# 模拟传感器噪声和传输干扰
# =============================================================================
enable_noise: false # 开关：噪声增强 (暂未实现)

# =============================================================================
# 预设配置示例
# =============================================================================

# Conservative configuration (light augmentation, maintain image quality)
conservative_config:
  aug_prob: 0.6
  image_size: 224
  enable_spatial: true
  enable_crop: true
  crop_scale: [0.9, 1.0]
  enable_affine: false
  enable_color: true
  enable_color_jitter: true
  brightness: 0.1
  contrast: 0.1
  saturation: 0.05
  hue: 0.02
  enable_grayscale: false
  enable_blur: false

# High resolution configuration (preserve more detail information)
high_resolution_config:
  aug_prob: 0.8
  image_size: 384 # Higher resolution
  enable_spatial: true
  enable_crop: true
  crop_scale: [0.85, 1.0] # Slightly conservative cropping
  crop_ratio: [0.95, 1.05] # More conservative aspect ratio
  enable_affine: true
  translate_range: [0.05, 0.05] # Smaller translation
  enable_color: true
  enable_color_jitter: true
  brightness: 0.15
  contrast: 0.15
  saturation: 0.1
  hue: 0.03
  enable_grayscale: true
  grayscale_prob: 0.05 # Reduce grayscale probability
  enable_blur: false # Disable blur to maintain clarity

# 激进配置 (强增强，最大化数据多样性)
aggressive_config:
  aug_prob: 0.9
  enable_spatial: true
  enable_crop: true
  crop_scale: [0.7, 1.0]
  crop_ratio: [0.8, 1.2]
  enable_affine: true
  translate_range: [0.15, 0.15]
  enable_color: true
  enable_color_jitter: true
  brightness: 0.3
  contrast: 0.3
  saturation: 0.2
  hue: 0.1
  enable_grayscale: true
  grayscale_prob: 0.15
  enable_blur: true
  blur_sigma: [0.1, 1.0]

# 仅空间增强 (只改变空间，不改变颜色)
spatial_only_config:
  aug_prob: 0.8
  enable_spatial: true
  enable_crop: true
  enable_affine: true
  enable_color: false
  enable_grayscale: false
  enable_blur: false

# 仅颜色增强 (只改变颜色，不改变空间)
color_only_config:
  aug_prob: 0.8
  enable_spatial: false
  enable_crop: false
  enable_affine: false
  enable_color: true
  enable_color_jitter: true
  enable_grayscale: true
  enable_blur: true
