# Grid V6 Experiment 3: Medium Rank + High Alpha + High Dropout + Linear
# 实验组合: r=24, alpha=64, dropout=0.1, scheduler=linear

name: "grid_v6_exp3_r24_a64_d10_linear"
description: "V6 Exp3: Medium rank with high alpha, high dropout, linear scheduler"

# Training Parameters
num_epochs: 15
batch_size: 8
learning_rate: 0.0001 # Conservative LR (Group A)
max_samples: 2068

# LoRA Parameters (Group 2: Medium)
lora_r: 24 # Medium rank
lora_alpha: 64 # High alpha (2.67:1 ratio)
lora_dropout: 0.1 # High dropout

# Optimization Parameters
warmup_steps: 250
max_grad_norm: 0.3

# Scheduler (Group 2: Linear)
scheduler_type: "linear"
start_factor: 0.1

# Early Stopping
early_stopping_enabled: true
early_stopping_patience: 3
min_delta: 0.001

# Data Parameters
val_split: 0.2
random_seed: 42
torch_dtype: "float32"
