# Grid V6 Experiment 4: Medium Rank + Low Alpha + Low Dropout + Cosine
# 实验组合: r=24, alpha=32, dropout=0.05, scheduler=cosine

name: "grid_v6_exp4_r24_a32_d05_cosine"
description: "V6 Exp4: Medium rank with low alpha, low dropout, cosine scheduler"

# Training Parameters
num_epochs: 15
batch_size: 8
learning_rate: 0.0002 # Higher LR (Group B)
max_samples: 2068

# LoRA Parameters (Group 2: Medium)
lora_r: 24 # Medium rank
lora_alpha: 32 # Low alpha (1.33:1 ratio)
lora_dropout: 0.05 # Low dropout

# Optimization Parameters
warmup_steps: 250
max_grad_norm: 0.3

# Scheduler (Group 1: Cosine)
scheduler_type: "cosine"
min_lr: 0.000001
cosine_restarts: false

# Early Stopping
early_stopping_enabled: true
early_stopping_patience: 3
min_delta: 0.001

# Data Parameters
val_split: 0.2
random_seed: 42
torch_dtype: "float32"
