# Grid V6 Experiment 2: Conservative Rank + Low Alpha + High Dropout + Linear
# 实验组合: r=16, alpha=32, dropout=0.1, scheduler=linear

name: "grid_v6_exp2_r16_a32_d10_linear"
description: "V6 Exp2: Conservative rank with low alpha, high dropout, linear scheduler"

# Training Parameters
num_epochs: 15
batch_size: 12
learning_rate: 0.0002 # Higher LR (Group B)
max_samples: 2068

# LoRA Parameters (Group 1: Conservative)
lora_r: 16 # Conservative rank
lora_alpha: 32 # Low alpha (2:1 ratio)
lora_dropout: 0.1 # High dropout

# Optimization Parameters
warmup_steps: 250
max_grad_norm: 0.3

# Scheduler (Group 2: Linear)
scheduler_type: "linear"
start_factor: 0.1

# Early Stopping
early_stopping_enabled: true
early_stopping_patience: 3
min_delta: 0.001

# Data Parameters
val_split: 0.2
random_seed: 42
torch_dtype: "float32"
