# Grid V6 Experiment 4 (Augmented): Medium Rank + Medium Alpha + Low Dropout + Cosine
# 实验组合: r=24, alpha=48, dropout=0.05, scheduler=cosine
# 使用数据增强数据集 (7755 samples, 3.75x augmentation)

name: "grid_v6_exp4_r24_a48_d05_cosine_augmented"
description: "V6 Exp4 Augmented: Medium rank with medium alpha, low dropout, cosine scheduler on augmented dataset"

# Training Parameters
num_epochs: 15
batch_size: 8
learning_rate: 0.0001 # Conservative LR (Group A)
max_samples: 7755 # Full augmented dataset

# LoRA Parameters (Group 2: Medium + Medium Alpha)
lora_r: 24 # Medium rank
lora_alpha: 48 # Medium alpha (2:1 ratio)
lora_dropout: 0.05 # Low dropout

# Optimization Parameters
warmup_steps: 250
max_grad_norm: 0.3

# Scheduler (Group 1: Cosine)
scheduler_type: "cosine"
min_lr: 0.000001
cosine_restarts: false

# Early Stopping
early_stopping_enabled: true
early_stopping_patience: 3
min_delta: 0.001

# Data Parameters
val_split: 0.2
random_seed: 42
torch_dtype: "float32"

# Data Source (使用增强数据集)
data_source: "augmented"
