# Grid V6 Experiment 8 (Augmented): High Rank + Medium Alpha + Low Dropout + Linear
# 实验组合: r=32, alpha=48, dropout=0.05, scheduler=linear
# 使用数据增强数据集 (7755 samples, 3.75x augmentation)

name: "grid_v6_exp8_r32_a48_d05_linear_augmented"
description: "V6 Exp8 Augmented: High rank with medium alpha, low dropout, linear scheduler on augmented dataset"

# Training Parameters
num_epochs: 15
batch_size: 8
learning_rate: 0.0001 # Conservative LR (Group A)
max_samples: 7755 # Full augmented dataset

# LoRA Parameters (Group 3: High + Medium Alpha)
lora_r: 32 # High rank
lora_alpha: 48 # Medium alpha (1.5:1 ratio)
lora_dropout: 0.05 # Low dropout

# Optimization Parameters
warmup_steps: 250
max_grad_norm: 0.3

# Scheduler (Group 2: Linear)
scheduler_type: "linear"
start_factor: 0.1

# Early Stopping
early_stopping_enabled: true
early_stopping_patience: 3
min_delta: 0.001

# Data Parameters
val_split: 0.2
random_seed: 42
torch_dtype: "float32"

# Data Source (使用增强数据集)
data_source: "augmented"
